// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/auction/v1/service.proto

package auction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Id:
	//	*GetRequest_AuctionId
	//	*GetRequest_ItemId
	Id isGetRequest_Id `protobuf_oneof:"id"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_auction_v1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_v1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_auction_v1_service_proto_rawDescGZIP(), []int{0}
}

func (m *GetRequest) GetId() isGetRequest_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (x *GetRequest) GetAuctionId() string {
	if x, ok := x.GetId().(*GetRequest_AuctionId); ok {
		return x.AuctionId
	}
	return ""
}

func (x *GetRequest) GetItemId() string {
	if x, ok := x.GetId().(*GetRequest_ItemId); ok {
		return x.ItemId
	}
	return ""
}

type isGetRequest_Id interface {
	isGetRequest_Id()
}

type GetRequest_AuctionId struct {
	AuctionId string `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3,oneof"`
}

type GetRequest_ItemId struct {
	ItemId string `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3,oneof"`
}

func (*GetRequest_AuctionId) isGetRequest_Id() {}

func (*GetRequest_ItemId) isGetRequest_Id() {}

type CreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId         string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	StartPrice     float64                `protobuf:"fixed64,3,opt,name=start_price,json=startPrice,proto3" json:"start_price,omitempty"`
	CurrentPrice   float64                `protobuf:"fixed64,4,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	ReservePrice   float64                `protobuf:"fixed64,5,opt,name=reserve_price,json=reservePrice,proto3" json:"reserve_price,omitempty"`
	IncrementPrice float64                `protobuf:"fixed64,6,opt,name=increment_price,json=incrementPrice,proto3" json:"increment_price,omitempty"`
	StartDate      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_auction_v1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_v1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_auction_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *CreateRequest) GetStartPrice() float64 {
	if x != nil {
		return x.StartPrice
	}
	return 0
}

func (x *CreateRequest) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *CreateRequest) GetReservePrice() float64 {
	if x != nil {
		return x.ReservePrice
	}
	return 0
}

func (x *CreateRequest) GetIncrementPrice() float64 {
	if x != nil {
		return x.IncrementPrice
	}
	return 0
}

func (x *CreateRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CreateRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type PlaceABidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Id:
	//	*PlaceABidRequest_AuctionId
	//	*PlaceABidRequest_ItemId
	Id     isPlaceABidRequest_Id `protobuf_oneof:"id"`
	Amount float64               `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *PlaceABidRequest) Reset() {
	*x = PlaceABidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_auction_v1_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceABidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceABidRequest) ProtoMessage() {}

func (x *PlaceABidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_v1_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceABidRequest.ProtoReflect.Descriptor instead.
func (*PlaceABidRequest) Descriptor() ([]byte, []int) {
	return file_api_auction_v1_service_proto_rawDescGZIP(), []int{2}
}

func (m *PlaceABidRequest) GetId() isPlaceABidRequest_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (x *PlaceABidRequest) GetAuctionId() string {
	if x, ok := x.GetId().(*PlaceABidRequest_AuctionId); ok {
		return x.AuctionId
	}
	return ""
}

func (x *PlaceABidRequest) GetItemId() string {
	if x, ok := x.GetId().(*PlaceABidRequest_ItemId); ok {
		return x.ItemId
	}
	return ""
}

func (x *PlaceABidRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type isPlaceABidRequest_Id interface {
	isPlaceABidRequest_Id()
}

type PlaceABidRequest_AuctionId struct {
	AuctionId string `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3,oneof"`
}

type PlaceABidRequest_ItemId struct {
	ItemId string `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3,oneof"`
}

func (*PlaceABidRequest_AuctionId) isPlaceABidRequest_Id() {}

func (*PlaceABidRequest_ItemId) isPlaceABidRequest_Id() {}

type PlaceABidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//	*PlaceABidResponse_Success
	//	*PlaceABidResponse_Error
	Result isPlaceABidResponse_Result `protobuf_oneof:"result"`
}

func (x *PlaceABidResponse) Reset() {
	*x = PlaceABidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_auction_v1_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceABidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceABidResponse) ProtoMessage() {}

func (x *PlaceABidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auction_v1_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceABidResponse.ProtoReflect.Descriptor instead.
func (*PlaceABidResponse) Descriptor() ([]byte, []int) {
	return file_api_auction_v1_service_proto_rawDescGZIP(), []int{3}
}

func (m *PlaceABidResponse) GetResult() isPlaceABidResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *PlaceABidResponse) GetSuccess() bool {
	if x, ok := x.GetResult().(*PlaceABidResponse_Success); ok {
		return x.Success
	}
	return false
}

func (x *PlaceABidResponse) GetError() string {
	if x, ok := x.GetResult().(*PlaceABidResponse_Error); ok {
		return x.Error
	}
	return ""
}

type isPlaceABidResponse_Result interface {
	isPlaceABidResponse_Result()
}

type PlaceABidResponse_Success struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3,oneof"`
}

type PlaceABidResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*PlaceABidResponse_Success) isPlaceABidResponse_Result() {}

func (*PlaceABidResponse_Error) isPlaceABidResponse_Result() {}

var File_api_auction_v1_service_proto protoreflect.FileDescriptor

var file_api_auction_v1_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0a, 0x61,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x09, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x07,
	0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x42, 0x04, 0x0a, 0x02, 0x69, 0x64, 0x22, 0xae, 0x02,
	0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x69, 0x6e,
	0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x6c,
	0x0a, 0x10, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x42, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0a, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x04, 0x0a, 0x02, 0x69, 0x64, 0x22, 0x51, 0x0a, 0x11,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x42, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32,
	0xe6, 0x01, 0x0a, 0x0e, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3c, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00,
	0x12, 0x42, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x42, 0x69,
	0x64, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x42, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x42, 0x69, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x76, 0x61, 0x72, 0x67, 0x61, 0x73, 0x2f, 0x61,
	0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31,
	0x3b, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_auction_v1_service_proto_rawDescOnce sync.Once
	file_api_auction_v1_service_proto_rawDescData = file_api_auction_v1_service_proto_rawDesc
)

func file_api_auction_v1_service_proto_rawDescGZIP() []byte {
	file_api_auction_v1_service_proto_rawDescOnce.Do(func() {
		file_api_auction_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_auction_v1_service_proto_rawDescData)
	})
	return file_api_auction_v1_service_proto_rawDescData
}

var file_api_auction_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_auction_v1_service_proto_goTypes = []interface{}{
	(*GetRequest)(nil),            // 0: api.auction.v1.GetRequest
	(*CreateRequest)(nil),         // 1: api.auction.v1.CreateRequest
	(*PlaceABidRequest)(nil),      // 2: api.auction.v1.PlaceABidRequest
	(*PlaceABidResponse)(nil),     // 3: api.auction.v1.PlaceABidResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*Auction)(nil),               // 5: api.auction.v1.Auction
}
var file_api_auction_v1_service_proto_depIdxs = []int32{
	4, // 0: api.auction.v1.CreateRequest.start_date:type_name -> google.protobuf.Timestamp
	4, // 1: api.auction.v1.CreateRequest.end_date:type_name -> google.protobuf.Timestamp
	0, // 2: api.auction.v1.AuctionService.Get:input_type -> api.auction.v1.GetRequest
	1, // 3: api.auction.v1.AuctionService.Create:input_type -> api.auction.v1.CreateRequest
	2, // 4: api.auction.v1.AuctionService.PlaceABid:input_type -> api.auction.v1.PlaceABidRequest
	5, // 5: api.auction.v1.AuctionService.Get:output_type -> api.auction.v1.Auction
	5, // 6: api.auction.v1.AuctionService.Create:output_type -> api.auction.v1.Auction
	3, // 7: api.auction.v1.AuctionService.PlaceABid:output_type -> api.auction.v1.PlaceABidResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_auction_v1_service_proto_init() }
func file_api_auction_v1_service_proto_init() {
	if File_api_auction_v1_service_proto != nil {
		return
	}
	file_api_auction_v1_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_auction_v1_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_auction_v1_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_auction_v1_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceABidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_auction_v1_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceABidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_auction_v1_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*GetRequest_AuctionId)(nil),
		(*GetRequest_ItemId)(nil),
	}
	file_api_auction_v1_service_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*PlaceABidRequest_AuctionId)(nil),
		(*PlaceABidRequest_ItemId)(nil),
	}
	file_api_auction_v1_service_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*PlaceABidResponse_Success)(nil),
		(*PlaceABidResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_auction_v1_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auction_v1_service_proto_goTypes,
		DependencyIndexes: file_api_auction_v1_service_proto_depIdxs,
		MessageInfos:      file_api_auction_v1_service_proto_msgTypes,
	}.Build()
	File_api_auction_v1_service_proto = out.File
	file_api_auction_v1_service_proto_rawDesc = nil
	file_api_auction_v1_service_proto_goTypes = nil
	file_api_auction_v1_service_proto_depIdxs = nil
}
