// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/property/v1/message.proto

package property

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Land struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LotSizeAcres float32 `protobuf:"fixed32,1,opt,name=lot_size_acres,json=lotSizeAcres,proto3" json:"lot_size_acres,omitempty"`
}

func (x *Land) Reset() {
	*x = Land{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_property_v1_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Land) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Land) ProtoMessage() {}

func (x *Land) ProtoReflect() protoreflect.Message {
	mi := &file_api_property_v1_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Land.ProtoReflect.Descriptor instead.
func (*Land) Descriptor() ([]byte, []int) {
	return file_api_property_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Land) GetLotSizeAcres() float32 {
	if x != nil {
		return x.LotSizeAcres
	}
	return 0
}

type Residential struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LotSizeAcres     float32 `protobuf:"fixed32,1,opt,name=lot_size_acres,json=lotSizeAcres,proto3" json:"lot_size_acres,omitempty"`
	ConstructionSize float32 `protobuf:"fixed32,2,opt,name=construction_size,json=constructionSize,proto3" json:"construction_size,omitempty"`
	Bathrooms        float32 `protobuf:"fixed32,4,opt,name=bathrooms,proto3" json:"bathrooms,omitempty"`
	Bedrooms         int32   `protobuf:"varint,5,opt,name=bedrooms,proto3" json:"bedrooms,omitempty"`
}

func (x *Residential) Reset() {
	*x = Residential{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_property_v1_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Residential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Residential) ProtoMessage() {}

func (x *Residential) ProtoReflect() protoreflect.Message {
	mi := &file_api_property_v1_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Residential.ProtoReflect.Descriptor instead.
func (*Residential) Descriptor() ([]byte, []int) {
	return file_api_property_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *Residential) GetLotSizeAcres() float32 {
	if x != nil {
		return x.LotSizeAcres
	}
	return 0
}

func (x *Residential) GetConstructionSize() float32 {
	if x != nil {
		return x.ConstructionSize
	}
	return 0
}

func (x *Residential) GetBathrooms() float32 {
	if x != nil {
		return x.Bathrooms
	}
	return 0
}

func (x *Residential) GetBedrooms() int32 {
	if x != nil {
		return x.Bedrooms
	}
	return 0
}

type Commercial struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LotSizeAcres     float32 `protobuf:"fixed32,1,opt,name=lot_size_acres,json=lotSizeAcres,proto3" json:"lot_size_acres,omitempty"`
	ConstructionSize float32 `protobuf:"fixed32,2,opt,name=construction_size,json=constructionSize,proto3" json:"construction_size,omitempty"`
}

func (x *Commercial) Reset() {
	*x = Commercial{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_property_v1_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commercial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commercial) ProtoMessage() {}

func (x *Commercial) ProtoReflect() protoreflect.Message {
	mi := &file_api_property_v1_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commercial.ProtoReflect.Descriptor instead.
func (*Commercial) Descriptor() ([]byte, []int) {
	return file_api_property_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *Commercial) GetLotSizeAcres() float32 {
	if x != nil {
		return x.LotSizeAcres
	}
	return 0
}

func (x *Commercial) GetConstructionSize() float32 {
	if x != nil {
		return x.ConstructionSize
	}
	return 0
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line_1  string `protobuf:"bytes,1,opt,name=line_1,json=line1,proto3" json:"line_1,omitempty"`
	Line_2  string `protobuf:"bytes,2,opt,name=line_2,json=line2,proto3" json:"line_2,omitempty"`
	City    string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	County  string `protobuf:"bytes,4,opt,name=county,proto3" json:"county,omitempty"`
	State   string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	ZipCode string `protobuf:"bytes,6,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_property_v1_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_api_property_v1_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_api_property_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *Address) GetLine_1() string {
	if x != nil {
		return x.Line_1
	}
	return ""
}

func (x *Address) GetLine_2() string {
	if x != nil {
		return x.Line_2
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetCounty() string {
	if x != nil {
		return x.County
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url  string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_property_v1_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_api_property_v1_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_api_property_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Property struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address *Address `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Images  []*Image `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	// Types that are assignable to Type:
	//	*Property_Land
	//	*Property_Residential
	//	*Property_Commercial
	Type isProperty_Type `protobuf_oneof:"type"`
}

func (x *Property) Reset() {
	*x = Property{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_property_v1_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_api_property_v1_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_api_property_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *Property) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Property) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Property) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (m *Property) GetType() isProperty_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Property) GetLand() *Land {
	if x, ok := x.GetType().(*Property_Land); ok {
		return x.Land
	}
	return nil
}

func (x *Property) GetResidential() *Residential {
	if x, ok := x.GetType().(*Property_Residential); ok {
		return x.Residential
	}
	return nil
}

func (x *Property) GetCommercial() *Commercial {
	if x, ok := x.GetType().(*Property_Commercial); ok {
		return x.Commercial
	}
	return nil
}

type isProperty_Type interface {
	isProperty_Type()
}

type Property_Land struct {
	Land *Land `protobuf:"bytes,3,opt,name=land,proto3,oneof"`
}

type Property_Residential struct {
	Residential *Residential `protobuf:"bytes,4,opt,name=residential,proto3,oneof"`
}

type Property_Commercial struct {
	Commercial *Commercial `protobuf:"bytes,5,opt,name=commercial,proto3,oneof"`
}

func (*Property_Land) isProperty_Type() {}

func (*Property_Residential) isProperty_Type() {}

func (*Property_Commercial) isProperty_Type() {}

var File_api_property_v1_message_proto protoreflect.FileDescriptor

var file_api_property_v1_message_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x2e, 0x76, 0x31,
	0x22, 0x2c, 0x0a, 0x04, 0x4c, 0x61, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6c, 0x6f, 0x74, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x5f, 0x61, 0x63, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0c, 0x6c, 0x6f, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x41, 0x63, 0x72, 0x65, 0x73, 0x22, 0x9a,
	0x01, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x24,
	0x0a, 0x0e, 0x6c, 0x6f, 0x74, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x61, 0x63, 0x72, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x6c, 0x6f, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x41,
	0x63, 0x72, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x10, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x68, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x62, 0x61, 0x74, 0x68, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x62, 0x65, 0x64, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x5f, 0x0a, 0x0a, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x69, 0x61, 0x6c, 0x12, 0x24, 0x0a, 0x0e, 0x6c, 0x6f, 0x74,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x61, 0x63, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0c, 0x6c, 0x6f, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x41, 0x63, 0x72, 0x65, 0x73, 0x12,
	0x2b, 0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x94, 0x01, 0x0a,
	0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x69, 0x6e, 0x65,
	0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x31, 0x12,
	0x15, 0x0a, 0x06, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x69, 0x6e, 0x65, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x7a, 0x69, 0x70, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x7a, 0x69, 0x70, 0x43,
	0x6f, 0x64, 0x65, 0x22, 0x2d, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x22, 0xb4, 0x02, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x32, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x64,
	0x12, 0x40, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x12, 0x3d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x69, 0x61, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63,
	0x69, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x69, 0x61,
	0x6c, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x76, 0x61, 0x72, 0x67, 0x61, 0x73, 0x2f,
	0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x2f,
	0x76, 0x31, 0x3b, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_property_v1_message_proto_rawDescOnce sync.Once
	file_api_property_v1_message_proto_rawDescData = file_api_property_v1_message_proto_rawDesc
)

func file_api_property_v1_message_proto_rawDescGZIP() []byte {
	file_api_property_v1_message_proto_rawDescOnce.Do(func() {
		file_api_property_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_property_v1_message_proto_rawDescData)
	})
	return file_api_property_v1_message_proto_rawDescData
}

var file_api_property_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_property_v1_message_proto_goTypes = []interface{}{
	(*Land)(nil),        // 0: api.property.v1.Land
	(*Residential)(nil), // 1: api.property.v1.Residential
	(*Commercial)(nil),  // 2: api.property.v1.Commercial
	(*Address)(nil),     // 3: api.property.v1.Address
	(*Image)(nil),       // 4: api.property.v1.Image
	(*Property)(nil),    // 5: api.property.v1.Property
}
var file_api_property_v1_message_proto_depIdxs = []int32{
	3, // 0: api.property.v1.Property.address:type_name -> api.property.v1.Address
	4, // 1: api.property.v1.Property.images:type_name -> api.property.v1.Image
	0, // 2: api.property.v1.Property.land:type_name -> api.property.v1.Land
	1, // 3: api.property.v1.Property.residential:type_name -> api.property.v1.Residential
	2, // 4: api.property.v1.Property.commercial:type_name -> api.property.v1.Commercial
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_property_v1_message_proto_init() }
func file_api_property_v1_message_proto_init() {
	if File_api_property_v1_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_property_v1_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Land); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_property_v1_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Residential); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_property_v1_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commercial); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_property_v1_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_property_v1_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_property_v1_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Property); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_property_v1_message_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*Property_Land)(nil),
		(*Property_Residential)(nil),
		(*Property_Commercial)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_property_v1_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_property_v1_message_proto_goTypes,
		DependencyIndexes: file_api_property_v1_message_proto_depIdxs,
		MessageInfos:      file_api_property_v1_message_proto_msgTypes,
	}.Build()
	File_api_property_v1_message_proto = out.File
	file_api_property_v1_message_proto_rawDesc = nil
	file_api_property_v1_message_proto_goTypes = nil
	file_api_property_v1_message_proto_depIdxs = nil
}
